### ISSUE TITLE
月曜9:00にデプロイのワークフローが動かない

### ISSUE THREAD

**Issue by uhooi** [ios-osushi/website#19]
## 概要

月曜日の 9:00 にデプロイのワークフローが動かない。
`cron: '0 0 * * 1'` の式が間違っている可能性が高い。
https://github.com/ios-osushi/website/blob/c7db9c2e5d85eac9aec8ed25dd35b15a67393f3b/.github/workflows/deploy.yml#L5

**Comment by ry-itto** [comment]
9:00 じゃなくて 10:00 とかに動いてる説ありますかね 🤔 
scheduled が動いていそうですが、 10:00 くらいに実行されていそう
https://github.com/ios-osushi/website/actions

**Comment by uhooi** [comment]
あれっホントだ
JST は UTC +0900 なのに…もしやサマータイム？

**Comment by ry-itto** [comment]
cron式でのスケジュールは max 1時間遅れてしまうっぽいですね 🤔 
いっそ、月曜8時とかにするとちょうどいいかも。。？
https://github.community/t/scheduled-action-running-consistently-late/138025/10

**Comment by uhooi** [comment]
サマータイムだったｗ
8:00 に変更します！！！
https://ja.wikipedia.org/wiki/%E8%8B%B1%E5%9B%BD%E5%A4%8F%E6%99%82%E9%96%93

**Comment by uhooi** [comment]
いや、UTC だと関係ないかも、あと +0800 になるから 10:00 でなく 8:00 に実行されないとおかしい…
わからんけど今より 1 時間早くすれば解決できるのは間違いないからそうしますｗ
