### ISSUE TITLE
RSS feedのdescriptionに概要が含まれてほしい

### ISSUE THREAD

**Issue by usami-k** [ios-osushi/website#22]
iOS Osushiの更新情報をSlackで通知してほしいと考えて、[RSS feed](https://ios-osushi.github.io/feed.rss) を利用しています。今朝、無事にSlackで通知を受け取ることができました（以下のスクショ）。リンクを開けばiOS Osushiの記事を開ける状態です。

<img width="429" alt="スクリーンショット 2022-04-04 17 32 30" src="https://user-images.githubusercontent.com/536781/161506060-f4a7f542-f957-41c5-8c85-7fe17107d81e.png">

ただ、リンクを開く前に内容がもう少しわかると嬉しいなと思っています。

現状のRSS feedは、titleが `001 2022-04-04` で description も同じ `001 2022-04-04` となっています。このdescriptionの内容がSlackの本文になっているように見えます。

このdescriptionにもう少し内容が含まれていてほしいです。どうでしょうか。

**Comment by uhooi** [comment]
RSS フィードの購読ありがとうございます…！
確かに仰る通りです、description にちゃんと内容の概要を含めるようにします 🙇

**Comment by uhooi** [comment]
@usami-k 
既存の記事の `description` と運用フローを修正したので、本 PR はクローズしますね！
次のデプロイ時に反映されます。

**Comment by usami-k** [comment]
いい感じで通知されるようになりました。ありがとうございます！

<img width="672" alt="スクリーンショット 2022-04-11 9 02 44" src="https://user-images.githubusercontent.com/536781/162645715-5cd1ce5f-1ac1-4810-b5c9-f07767e95eec.png">
