### ISSUE TITLE
Twitterでの周知を自動化する

### ISSUE THREAD

**Issue by uhooi** [ios-osushi/website#4]
以下の作業を自動化したい。
https://github.com/ios-osushi/wiki/blob/fc34c5aa5b6fd46f118eac9a6160dc32cd32a8c6/operation-flow.md#twitterでの周知

**Comment by uhooi** [comment]
Twitter の投稿は忘れがちだから、やはり自動化したいところ。

**Comment by KaitoMuraoka** [comment]
Twitter（現X）では一部有料となっているが、週一投稿なので、Freeプランでも問題なさそう

参考：https://developer.twitter.com/en/portal/products/free

**Comment by uhooi** [comment]
#182 と重複しているので、こちらはクローズとする。
