### ISSUE TITLE
起動中のサーバーが中断されると再度サーバーを立ち上げることが出来ない

### ISSUE THREAD

**Issue by hiro-nagami** [ios-osushi/website#57]
## 概要
起動中のサーバーが中断されると、ポートが開放されず再度サーバーを立ち上げることが出来ない。

![スクリーンショット 2022-05-29 7 04 04](https://user-images.githubusercontent.com/25496478/170844309-ae80368f-d76c-443d-8bbd-f003880f13d9.png)

中断時は以下のエラーが発生している。

![スクリーンショット 2022-05-29 7 04 39](https://user-images.githubusercontent.com/25496478/170844306-2dd54062-746b-4d1d-9d98-739a58e21ad3.png)

## 再現手順
1. `make run` でサーバーを起動
2.  Ctrl+ Cでサーバーを停止

## 修正しないとどう困るか
毎度、プロセスからkillを行う必要がある。

## 修正案
修正する必要まではないと思いますが、Ctrl+Cなどで中断してしまった場合のkill方法の案内などがあると助かるかなと思いました。

**Comment by uhooi** [comment]
ご報告ありがとうございますー！
Ctrl + C で中断したことがないので気づけませんでした、、
Publish の問題なので、iOS Osushi 側の README に書くのも微妙で悩ましいですね、、
https://github.com/JohnSundell/Publish

**Comment by uhooi** [comment]
Publish ですでに PR が作成されていました！
https://github.com/JohnSundell/Publish/pull/82

そのためこちらはクローズします 🙏

**Comment by hiro-nagami** [comment]
お、新しいバージョンがリリースされれば修正されそうですね！了解です！
