### ISSUE TITLE
iOS関連ニュース報告

### ISSUE THREAD

**Issue by hiro-nagami** [ios-osushi/website#62]
## 概要
AppleがApple Watchのデジタルクラウンにカメラを内蔵する特許を取得。

## リンク

Apple has Won a Patent for a Future Apple Watch with an Integrated Camera in its Digital Crown and more
- https://www.patentlyapple.com/2022/05/apple-has-won-a-patent-for-a-future-apple-watch-with-an-integrated-camera-in-its-digital-crown-and-more.html

US Patent & Trademark Office, Patent Full Text and Image Database
- https://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&u=%2Fnetahtml%2FPTO%2Fsearch-adv.htm&r=1&f=G&l=50&d=PTXT&p=1&S1=11,347,189&OS=11,347,189&RS=11,347,189

Apple Watchのデジタルクラウンにカメラを内蔵する特許取得
- https://iphone-mania.jp/news-459038/

**Comment by uhooi** [comment]
@hiro-nagami 情報ありがとうございます！
非常に嬉しいのですが、こちらは Apple が公式に公開している情報でしょうか？
もし異なる場合、リーク情報に近いので iOS Osushi では扱いづらいです、、

**Comment by hiro-nagami** [comment]
@uhooi 
リークというよりは、2つ目のリンクが米国特許庁特許検索データベース (https://patft.uspto.gov/) からの情報かと思います。２つ目のリンクがデータベースの登録情報のリンクになっています。実際に辿ってみたらありました。

米国特許庁特許検索データベースについては下記を参考にしてもらえると:pray:
https://rnavi.ndl.go.jp/research_guide/entry/theme-honbun-400036.php

もし扱えなさそうであればCloseしていただいて大丈夫です:ok_man:

**Comment by uhooi** [comment]
@hiro-nagami すみません、言葉足らずでした 🙏 
特許を取ったのは事実だと思いますが、Apple がこの情報を公開したいなら自ら行うと思います。
積極的に公開したい情報でない場合を考慮し、iOS Osushi では Apple の正式発表前に取り上げるのは避けたいです。

**Comment by hiro-nagami** [comment]
承知です！
それではクローズしちゃいますねー
