### ISSUE TITLE
macOS Big Sur 11.6.7 マイナーパッチリリース

### ISSUE THREAD

**Issue by hiro-nagami** [ios-osushi/website#66]
情報提供です。
Appleがセキュリティアップデートを含む macOS Big Sur 11.6.7 のマイナーアップデートをリリースしたようですね。

**Comment by ry-itto** [comment]
情報提供ありがとうございます！
折角のところ申し訳ありませんが、Apple 公式からの公開情報が見つけられなかったこともあり、記事には載せない方針とさせていただきます 🙏🏼

**Comment by ry-itto** [comment]
一度クローズしたところで申し訳ありません 🙇🏼 

Apple 公式のソースを発見したのですが、これまでセキュリティアップデートについて記事で掲載するようにしていなかったため、一度運営で持ち帰り検討させていただきます！
掲載することになりましたら、最後こちらで返信をさせていただければと思います 🙏🏼 

https://support.apple.com/ja-jp/HT201222
