### ISSUE TITLE
textlintをCIに導入する

### ISSUE THREAD

**Issue by uhooi** [ios-osushi/website#7]
## 参考

- https://github.com/ios-osushi/website/pull/1#issuecomment-1079940458
- https://zenn.dev/yuta28/articles/blog-lint-ci-reviewdog

**Comment by ry-itto** [comment]
textlint と別途みたいになるかもですが wiki に書いている執筆ルールを自動チェックしてくれる lint をコマンド追加したりしたいですね。。！

**Comment by uhooi** [comment]
それはしたい…！
もし textlint で実現できなくても、RedPen や prh などでできるかも！？
