### ISSUE TITLE
適用開始が延長されていたApp Store Review Guidelineの適用開始

### ISSUE THREAD

**Issue by hiro-nagami** [ios-osushi/website#74]
## 提供情報

- 3.1.1 オンラインのグループイベントのApp内課金 
    - 適用開始予定日： 2022年6月30日
    - https://developer.apple.com/jp/news/?id=i71db0mv

- 5.1.1 App内のアカウント削除機能の提供
    - 適用開始予定日： 2022年6月30日
    - https://developer.apple.com/jp/news/?id=i71db0mv

**Comment by treastrain** [comment]
情報提供いただきありがとうございます！

App Store Review [ガイドライン 5.1.1](https://developer.apple.com/jp/app-store/review/guidelines/#5.1.1) の適用開始日延期については、[iOS Osushi 第009回](https://github.com/ios-osushi/website/blob/56cd0289c62f273879bc8dd06c286c18522afba5/Content/posts/009-20220530.md?plain=1#L38)で紹介済みの内容でした。

また、App Store Review [ガイドライン3.1.1](https://developer.apple.com/jp/app-store/review/guidelines/#3.1.1) と合わせても、延期された適用開始日直前または以降に Apple ないし Apple Developer 側から新規にニュースリリース等は発表されていないことから、次回の iOS Osushi で取り上げる優先度は 低 とさせていただきます。

改めまして、この度はご協力くださいましてありがとうございました！
